import { PatternData } from "../utils/types";

export const patterns: PatternData[] = [
  {
    id: '12',
    patternName: 'Sailor\'s Dress',
    comments: 'A lovely little sew but took foreeeeever to get the buttons done',
    printed: false,
    projectorFriendly: true,
    files: ['link.to.file.one.pdf', 'link.to.projector.file.pdf', 'link.to.kids.size.pdf'],
    imageSrc: 'https://picsum.photos/200?random=1',
    company: 'SewNautical',
    patternUrl: 'https://example.com/sailors-dress-pattern',
    tags: ['Summer', 'Dress', 'Intermediate']
  },
  {
    id: '1',
    patternName: 'Funky Kids Dress',
    comments: 'Great pattern for beginners',
    printed: true,
    projectorFriendly: false,
    files: ['pattern.pdf', 'instructions.pdf'],
    imageSrc: 'https://picsum.photos/200?random=2',
    company: 'FunStitches',
    patternUrl: 'https://example.com/funky-kids-dress-pattern',
    tags: ['Summer', 'Kids', 'Dress', 'Easy']
  },
  {
    id: '2',
    patternName: 'Cool Men\'s T-Shirt',
    comments: 'Includes different sleeve options',
    printed: false,
    projectorFriendly: true,
    files: ['pattern.pdf', 'instructions.pdf'],
    imageSrc: 'https://picsum.photos/200?random=3',
    company: 'MachoStitch',
    patternUrl: 'https://example.com/mens-tshirt-pattern',
    tags: ['Men', 'T-Shirt', 'Intermediate']
  },
  {
    id: '3',
    patternName: 'Artsy Craft Apron',
    comments: 'Perfect for crafting activities',
    printed: true,
    projectorFriendly: false,
    files: ['pattern.pdf', 'instructions.pdf'],
    imageSrc: 'https://picsum.photos/200?random=4',
    company: 'CreativeStitch',
    patternUrl: 'https://example.com/artsy-craft-apron-pattern',
    tags: ['Crafts', 'Apron', 'Easy']
  },
  {
    id: '4',
    patternName: 'Whimsical Unisex Pouch',
    comments: 'Versatile pouch for various uses',
    printed: true,
    projectorFriendly: true,
    files: ['pattern.pdf', 'instructions.pdf'],
    imageSrc: 'https://picsum.photos/200?random=15',
    company: 'DreamStitches',
    patternUrl: 'https://example.com/unisex-pouch-pattern',
    tags: ['Unisex', 'Pouch', 'Beginner']
  },
  {
    id: '5',
    patternName: 'Playful Kids Overalls',
    comments: 'Includes adjustable straps',
    printed: true,
    projectorFriendly: false,
    files: ['pattern.pdf', 'instructions.pdf'],
    imageSrc: 'https://picsum.photos/200?random=137',
    company: 'TinyStitches',
    patternUrl: 'https://example.com/kids-overalls-pattern',
    tags: ['Kids', 'Overalls', 'Intermediate']
  },
  {
    id: '6',
    patternName: 'Elegant Women\'s Blouse',
    comments: 'Requires precise sewing techniques',
    printed: false,
    projectorFriendly: false,
    files: ['pattern.pdf', 'instructions.pdf'],
    imageSrc: 'https://picsum.photos/200?random=13',
    company: 'ChicStitch',
    patternUrl: 'https://example.com/womens-blouse-pattern',
    tags: ['Women', 'Blouse', 'Advanced']
  },
  {
    id: '7',
    patternName: 'Quirky Craft Tote Bag',
    comments: 'Spacious bag for craft supplies',
    printed: true,
    projectorFriendly: true,
    files: ['pattern.pdf', 'instructions.pdf'],
    imageSrc: 'https://picsum.photos/200?random=178',
    company: 'FunkyStitch',
    patternUrl: 'https://example.com/craft-tote-bag-pattern',
    tags: ['Crafts', 'Tote Bag', 'Easy']
  },
  {
    id: '8',
    patternName: 'Adorable Kids Costume',
    comments: 'Fun costume for dress-up play',
    printed: true,
    projectorFriendly: false,
    files: ['pattern.pdf', 'instructions.pdf'],
    imageSrc: 'https://picsum.photos/200?random=98',
    company: 'PlayfulPatterns',
    patternUrl: 'https://example.com/kids-costume-pattern',
    tags: ['Kids', 'Costume', 'Intermediate']
  },
  {
    id: '9',
    patternName: 'Fashionable Men\'s Skirt',
    comments: 'Includes lining and zipper',
    printed: true,
    projectorFriendly: false,
    files: ['pattern.pdf', 'instructions.pdf'],
    imageSrc: 'https://picsum.photos/200?random=75',
    company: 'TrendyStitch',
    patternUrl: 'https://example.com/mens-skirt-pattern',
    tags: ['Men', 'Skirt', 'Intermediate']
  },
  {
    id: '10',
    patternName: 'Creative Craft Pillow Cover',
    comments: 'Great for home decoration',
    printed: true,
    projectorFriendly: false,
    files: ['pattern.pdf', 'instructions.pdf'],
    imageSrc: 'https://picsum.photos/200?random=42',
    company: 'ArtisticStitch',
    patternUrl: 'https://example.com/craft-pillow-cover-pattern',
    tags: ['Crafts', 'Pillow Cover', 'Beginner']
  },
  {
    id: '11',
    patternName: 'Magical Kids Romper',
    comments: 'Includes snap fasteners',
    printed: true,
    projectorFriendly: false,
    files: ['pattern.pdf', 'instructions.pdf'],
    imageSrc: 'https://picsum.photos/200?random=32',
    company: 'WhimsyPatterns',
    patternUrl: 'https://example.com/kids-romper-pattern',
    tags: ['Kids', 'Romper', 'Intermediate']
  },
];
