type PatternData = {
  id : string,
  name: string,
  hobby: string,
  category: string,
  subcategory: string, 
  fabric: string, 
  season: string,
  difficulty: string, 
  comments: string, 
  printed: boolean,
  projectorFriendly: boolean,
  files: string[]
};

const data: PatternData[] = [
  { 
    id: '12',
    name: 'Sailor\'s Dress',
    hobby: 'Sewing',
    category: 'Womens',
    subcategory: 'Dress',
    fabric: 'Woven',
    season: 'Summer',
    difficulty: 'Intermediate',
    comments: 'A lovely little sew but took foreeeeever to get the buttons done',
    printed: false,
    projectorFriendly: true,
    files: ['link.to.file.one.pdf', 'link.to.projector.file.pdf', 'link.to.kids.size.pdf']
  },
  {
    id: '1',
    name: 'Funky Kids Dress',
    hobby: 'Sewing',
    category: 'kids',
    subcategory: 'Dress',
    fabric: 'Cotton',
    season: 'Summer',
    difficulty: 'Easy',
    comments: 'Great pattern for beginners',
    printed: true,
    projectorFriendly: false,
    files: ['pattern.pdf', 'instructions.pdf']
  },
  {
    id: '2',
    name: 'Cool Men\'s T-Shirt',
    hobby: 'Sewing',
    category: 'mens',
    subcategory: 'T-Shirt',
    fabric: 'Jersey',
    season: 'All seasons',
    difficulty: 'Intermediate',
    comments: 'Includes different sleeve options',
    printed: false,
    projectorFriendly: true,
    files: ['pattern.pdf', 'instructions.pdf']
  },
  {
    id: '3',
    name: 'Artsy Craft Apron',
    hobby: 'Sewing',
    category: 'crafts',
    subcategory: 'Apron',
    fabric: 'Canvas',
    season: 'All seasons',
    difficulty: 'Easy',
    comments: 'Perfect for crafting activities',
    printed: true,
    projectorFriendly: false,
    files: ['pattern.pdf', 'instructions.pdf']
  },
  {
    id: '4',
    name: 'Whimsical Unisex Pouch',
    hobby: 'Sewing',
    category: 'unisex',
    subcategory: 'Pouch',
    fabric: 'Linen',
    season: 'All seasons',
    difficulty: 'Beginner',
    comments: 'Versatile pouch for various uses',
    printed: true,
    projectorFriendly: true,
    files: ['pattern.pdf', 'instructions.pdf']
  },
  {
    id: '5',
    name: 'Playful Kids Overalls',
    hobby: 'Sewing',
    category: 'kids',
    subcategory: 'Overalls',
    fabric: 'Denim',
    season: 'Spring, Fall',
    difficulty: 'Intermediate',
    comments: 'Includes adjustable straps',
    printed: true,
    projectorFriendly: false,
    files: ['pattern.pdf', 'instructions.pdf']
  },
  {
    id: '6',
    name: 'Elegant Women\'s Blouse',
    hobby: 'Sewing',
    category: 'womens',
    subcategory: 'Blouse',
    fabric: 'Chiffon',
    season: 'Summer',
    difficulty: 'Advanced',
    comments: 'Requires precise sewing techniques',
    printed: false,
    projectorFriendly: false,
    files: ['pattern.pdf', 'instructions.pdf']
  },
  {
    id: '7',
    name: 'Quirky Craft Tote Bag',
    hobby: 'Sewing',
    category: 'crafts',
    subcategory: 'Tote Bag',
    fabric: 'Cotton',
    season: 'All seasons',
    difficulty: 'Easy',
    comments: 'Spacious bag for craft supplies',
    printed: true,
    projectorFriendly: true,
    files: ['pattern.pdf', 'instructions.pdf']
  },
  {
    id: '8',
    name: 'Adorable Kids Costume',
    hobby: 'Sewing',
    category: 'kids',
    subcategory: 'Costume',
    fabric: 'Fleece',
    season: 'All seasons',
    difficulty: 'Intermediate',
    comments: 'Fun costume for dress-up play',
    printed: true,
    projectorFriendly: false,
    files: ['pattern.pdf', 'instructions.pdf']
  },
  {
    id: '9',
    name: 'Fashionable Men\'s Skirt',
    hobby: 'Sewing',
    category: 'mens',
    subcategory: 'Skirt',
    fabric: 'Wool',
    season: 'Winter',
    difficulty: 'Intermediate',
    comments: 'Includes lining and zipper',
    printed: true,
    projectorFriendly: false,
    files: ['pattern.pdf', 'instructions.pdf']
  },
  {
    id: '10',
    name: 'Creative Craft Pillow Cover',
    hobby: 'Sewing',
    category: 'crafts',
    subcategory: 'Pillow Cover',
    fabric: 'Cotton',
    season: 'All seasons',
    difficulty: 'Beginner',
    comments: 'Great for home decoration',
    printed: true,
    projectorFriendly: false,
    files: ['pattern.pdf', 'instructions.pdf']
  },
  {
    id: '11',
    name: 'Magical Kids Romper',
    hobby: 'Sewing',
    category: 'kids',
    subcategory: 'Romper',
    fabric: 'Jersey',
    season: 'Summer',
    difficulty: 'Intermediate',
    comments: 'Includes snap fasteners',
    printed: true,
    projectorFriendly: false,
    files: ['pattern.pdf', 'instructions.pdf']
  },
];

